// Package mimes provides Hydrus MIME lookup tables used by compatibility API
// responses.
package mimes

import "strings"

// Info is the Hydrus-facing metadata for a MIME enum.
type Info struct {
	Human    string
	Mimetype string
	Ext      string
}

// Lookup returns Hydrus-compatible MIME information for the supplied enum.
func Lookup(mime int) Info {
	info := Info{
		Human:    humanLookup[101],
		Mimetype: mimetypeLookup[101],
		Ext:      extLookup[101],
	}

	if value, ok := humanLookup[mime]; ok {
		info.Human = value
	}

	if value, ok := mimetypeLookup[mime]; ok {
		info.Mimetype = value
	}

	if value, ok := extLookup[mime]; ok {
		info.Ext = value
	}

	return info
}

// FromMIMEType resolves a supported import MIME type into the closest Hydrus
// filetype enum used by the current migration slices.
func FromMIMEType(value string) (int, bool) {
	normalized := strings.ToLower(strings.TrimSpace(value))
	mime, ok := importMIMETypeLookup[normalized]
	return mime, ok
}

// FromExtension resolves a supported file extension into the closest Hydrus
// filetype enum used by the current migration slices.
func FromExtension(value string) (int, bool) {
	normalized := strings.ToLower(strings.TrimSpace(value))
	mime, ok := importExtensionLookup[normalized]
	return mime, ok
}

var humanLookup = map[int]string{
	0:   "collection",
	1:   "jpeg",
	2:   "png",
	3:   "animated gif",
	4:   "bitmap",
	5:   "flash",
	6:   "yaml",
	7:   "icon",
	8:   "html",
	9:   "flv",
	10:  "pdf",
	11:  "zip",
	12:  "application/hydrus-encrypted-zip",
	13:  "mp3",
	14:  "mp4",
	15:  "ogg",
	16:  "flac",
	17:  "wma",
	18:  "wmv",
	19:  "wma or wmv",
	20:  "matroska",
	21:  "webm",
	22:  "json",
	23:  "apng",
	24:  "png or apng",
	25:  "mpeg",
	26:  "quicktime",
	27:  "avi",
	28:  "application/hydrus-update-definitions",
	29:  "application/hydrus-update-content",
	30:  "plaintext",
	31:  "rar",
	32:  "7z",
	33:  "webp",
	34:  "tiff",
	35:  "psd",
	36:  "m4a",
	37:  "realvideo",
	38:  "realaudio",
	39:  "tta",
	40:  "audio",
	41:  "image",
	42:  "video",
	43:  "application",
	44:  "animation",
	45:  "clip",
	46:  "wave",
	47:  "ogv",
	48:  "matroska audio",
	49:  "mp4 audio",
	50:  "mp4 with or without audio",
	51:  "cbor",
	52:  "windows exe",
	53:  "wavpack",
	54:  "sai2",
	55:  "krita",
	56:  "svg",
	57:  "xcf",
	58:  "gzip",
	59:  "archive",
	60:  "image project file",
	61:  "heif",
	62:  "heif sequence",
	63:  "heic",
	64:  "heic sequence",
	65:  "avif",
	66:  "avif sequence",
	68:  "static gif",
	69:  "procreate",
	70:  "qoi",
	71:  "epub",
	72:  "djvu",
	73:  "cbz",
	74:  "ugoira",
	75:  "rtf",
	76:  "docx",
	77:  "xlsx",
	78:  "pptx",
	79:  "ole file",
	80:  "doc",
	81:  "xls",
	82:  "ppt",
	83:  "animated webp",
	84:  "webp with or without animation",
	85:  "jxl",
	86:  "paint.net",
	87:  "jxl with or without animation",
	88:  "animated jxl",
	89:  "ora",
	100: "application/octet-stream",
	101: "unknown filetype",
}

var mimetypeLookup = map[int]string{
	0:   "collection",
	1:   "image/jpeg",
	2:   "image/png",
	3:   "image/gif",
	4:   "image/bmp",
	5:   "application/x-shockwave-flash",
	6:   "application/x-yaml",
	7:   "image/x-icon",
	8:   "text/html",
	9:   "video/x-flv",
	10:  "application/pdf",
	11:  "application/zip",
	12:  "application/hydrus-encrypted-zip",
	13:  "audio/mp3",
	14:  "video/mp4",
	15:  "audio/ogg",
	16:  "audio/flac",
	17:  "audio/x-ms-wma",
	18:  "video/x-ms-wmv",
	19:  "audio/x-ms-wma or video/x-ms-wmv",
	20:  "video/x-matroska",
	21:  "video/webm",
	22:  "application/json",
	23:  "image/apng",
	24:  "image/png or image/apng",
	25:  "video/mpeg",
	26:  "video/quicktime",
	27:  "video/x-msvideo",
	28:  "application/hydrus-update-definitions",
	29:  "application/hydrus-update-content",
	30:  "text/plain",
	31:  "application/vnd.rar",
	32:  "application/x-7z-compressed",
	33:  "image/webp",
	34:  "image/tiff",
	35:  "image/vnd.adobe.photoshop",
	36:  "audio/mp4",
	37:  "video/vnd.rn-realvideo",
	38:  "audio/vnd.rn-realaudio",
	39:  "audio/x-tta",
	40:  "audio",
	41:  "image",
	42:  "video",
	43:  "application",
	44:  "animation",
	45:  "application/clip",
	46:  "audio/x-wav",
	47:  "video/ogg",
	48:  "audio/x-matroska",
	49:  "audio/mp4",
	50:  "audio/mp4 or video/mp4",
	51:  "application/cbor",
	52:  "application/octet-stream",
	53:  "audio/wavpack",
	54:  "application/sai2",
	55:  "application/x-krita",
	56:  "image/svg+xml",
	57:  "image/x-xcf",
	58:  "application/gzip",
	59:  "archive",
	60:  "image project file",
	61:  "image/heif",
	62:  "image/heif-sequence",
	63:  "image/heic",
	64:  "image/heic-sequence",
	65:  "image/avif",
	66:  "image/avif-sequence",
	68:  "image/gif",
	69:  "application/x-procreate",
	70:  "image/qoi",
	71:  "application/epub+zip",
	72:  "image/vnd.djvu",
	73:  "application/vnd.comicbook+zip",
	74:  "application/zip",
	75:  "application/rtf",
	76:  "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
	77:  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
	78:  "application/vnd.openxmlformats-officedocument.presentationml.presentation",
	79:  "application/x-ole-storage",
	80:  "application/msword",
	81:  "application/vnd.ms-excel",
	82:  "application/vnd.ms-powerpoint",
	83:  "image/webp",
	84:  "image/webp, static or animated",
	85:  "image/jxl",
	86:  "application/x-paintnet",
	87:  "image/jxl, static or animated",
	88:  "image/jxl",
	89:  "image/openraster",
	100: "application/octet-stream",
	101: "unknown filetype",
}

var extLookup = map[int]string{
	0:   ".collection",
	1:   ".jpg",
	2:   ".png",
	3:   ".gif",
	4:   ".bmp",
	5:   ".swf",
	6:   ".yaml",
	7:   ".ico",
	8:   ".html",
	9:   ".flv",
	10:  ".pdf",
	11:  ".zip",
	12:  ".zip.encrypted",
	13:  ".mp3",
	14:  ".mp4",
	15:  ".ogg",
	16:  ".flac",
	17:  ".wma",
	18:  ".wmv",
	20:  ".mkv",
	21:  ".webm",
	22:  ".json",
	23:  ".png",
	25:  ".mpeg",
	26:  ".mov",
	27:  ".avi",
	28:  "",
	29:  "",
	30:  ".txt",
	31:  ".rar",
	32:  ".7z",
	33:  ".webp",
	34:  ".tiff",
	35:  ".psd",
	36:  ".m4a",
	37:  ".rm",
	38:  ".ra",
	39:  ".tta",
	45:  ".clip",
	46:  ".wav",
	47:  ".ogv",
	48:  ".mkv",
	49:  ".mp4",
	52:  ".exe",
	53:  ".wv",
	54:  ".sai2",
	55:  ".kra",
	56:  ".svg",
	57:  ".xcf",
	58:  ".gz",
	61:  ".heif",
	62:  ".heifs",
	63:  ".heic",
	64:  ".heics",
	65:  ".avif",
	66:  ".avifs",
	68:  ".gif",
	69:  ".procreate",
	70:  ".qoi",
	71:  ".epub",
	72:  ".djvu",
	73:  ".cbz",
	74:  ".zip",
	75:  ".rtf",
	76:  ".docx",
	77:  ".xlsx",
	78:  ".pptx",
	80:  ".doc",
	81:  ".xls",
	82:  ".ppt",
	83:  ".webp",
	85:  ".jxl",
	86:  ".pdn",
	88:  ".jxl",
	89:  ".ora",
	100: ".bin",
	101: "",
}

var importMIMETypeLookup = map[string]int{
	"application/pdf":  10,
	"application/zip":  11,
	"audio/flac":       16,
	"audio/mpeg":       13,
	"audio/mp3":        13,
	"audio/wav":        46,
	"image/apng":       23,
	"image/bmp":        4,
	"image/avif":       65,
	"image/gif":        3,
	"image/heic":       63,
	"image/heif":       61,
	"image/jxl":        85,
	"image/jpeg":       1,
	"image/png":        2,
	"image/qoi":        70,
	"image/svg+xml":    56,
	"image/tiff":       34,
	"image/x-icon":     7,
	"image/webp":       33,
	"text/plain":       30,
	"video/mpeg":       25,
	"video/mp4":        14,
	"video/ogg":        47,
	"video/quicktime":  26,
	"video/webm":       21,
	"video/x-matroska": 20,
	"video/x-msvideo":  27,
}

var importExtensionLookup = map[string]int{
	".apng": 23,
	".avif": 65,
	".bmp":  4,
	".flac": 16,
	".gif":  3,
	".heic": 63,
	".heif": 61,
	".ico":  7,
	".jpeg": 1,
	".jxl":  85,
	".jpg":  1,
	".mkv":  20,
	".mov":  26,
	".mp3":  13,
	".mp4":  14,
	".mpeg": 25,
	".mpg":  25,
	".ogv":  47,
	".pdf":  10,
	".png":  2,
	".qoi":  70,
	".svg":  56,
	".tif":  34,
	".tiff": 34,
	".txt":  30,
	".avi":  27,
	".wav":  46,
	".webm": 21,
	".webp": 33,
	".zip":  11,
}
